name: 테스트용 배포

# franchise list
env:
  FRANCHISE_LIST: '["kyochon","eupcheonri"]'

on:
  push:
    branches:
      - main


# Allow one concurrent deployment
concurrency:
  group: "multifranchise-${{ github.event.inputs.env }}"
  cancel-in-progress: false

jobs:
  determine-modules:
    runs-on: ubuntu-latest
    outputs:
      modules-to-build: ${{ steps.set-modules.outputs.modules-to-build }}
      franchises: ${{ steps.set-modules.outputs.franchises }}
      json-array: ${{ steps.set-modules.outputs.json-array }}
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 레포지토리 파일 체크아웃

      - name: List files in workspace
        run: |
          ls -al
          echo "NEXT"
          ls -la /github/workspace

      - name: Send GitHub Action trigger data to Slack workflow
        uses: ghkdqhrbals/slack-list@v1.0.5
        with:
          slack-webhook-url: 'https://hooks.slack.com/services/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'
          actor: ${{ github.actor }}
          messages: '["test1", "test2", "test3"]'
          message-title: 'Testing Slack Notification Header'
          color: '#3bb143'